import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';

const Home: NextPage = () => {
  const [show, setShow] = useState(false);
    
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => {
        setShow(true)
      }}>Invite Bot</button>
      {show ? (<>
        <embed src="https://discord.com/api/oauth2/authorize?client_id=998143543178690590&permissions=8&scope=bot"/>
      </>):(<></>)}
    </div>
  )
}

export default Home
